version: '3'
services:
  # nginx:
  #   build:
  #     context: ./
  #     dockerfile: ./production/web/Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - 80:80
  #   env_file:
  #     - .env
  #   depends_on:
  #     - server
  #   networks:
  #     - frontend
  #     - backend

  server:
    build:
      context: ./production/server
    restart: unless-stopped
    hostname: server
    env_file:
      - .env
    environment:
      NODE_ENV: production
    networks:
      - backend
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - "./production/server/:/var/www/server/"

  db:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: unless-stopped
    hostname: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      TZ: "Europe/Warsaw"
    volumes:
      - "./database/init/:/docker-entrypoint-initdb.d/"
    networks:
      - backend
    env_file:
      - .env
    ports:
      - 27017:27017

networks:
  backend:
  frontend:
